// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBqTOZ1t0zMJHMETOTItm8AeXl-c2B0I',
    appId: '1:971350406704:android:10143b0ae156dca0e09ff5',
    messagingSenderId: '971350406704',
    projectId: 'pruebas-fire-base',
    databaseURL: 'https://pruebas-fire-base.firebaseio.com',
    storageBucket: 'pruebas-fire-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XkcaMrDy-ilebIjiWGh2NpQHWxaUcno',
    appId: '1:971350406704:ios:00951937c0f0a15ae09ff5',
    messagingSenderId: '971350406704',
    projectId: 'pruebas-fire-base',
    databaseURL: 'https://pruebas-fire-base.firebaseio.com',
    storageBucket: 'pruebas-fire-base.appspot.com',
    androidClientId: '971350406704-fpd6uii8ibjpcjem0i9jpcred1su0vca.apps.googleusercontent.com',
    iosClientId: '971350406704-cgdo7eh16qc7nihhns7mkrk6p01gbvf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbServiceTestApp',
  );
}
